# Generated by Django 4.0.1 on 2022-01-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0002_alter_ticket_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='picture',
        ),
    ]
